# EC2NodeClass PDN: AL2023 optimizado → Ahorro 40% EBS (60GB max vs 100GB: ~$3/nodo/mes).
# Beneficios: Compatible original, resize smart pero reducido.
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: pdn-ec2-spot
spec:
  amiFamily: AL2023
  amiSelectorTerms:
  - alias: al2023@latest/karpenter  # ← **Auto-update**.
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      deleteOnTermination: true
      volumeSize: 30Gi  # Inicial ok.
      volumeType: gp3
      encrypted: true
      iops: 3000  # Optimizado.
  metadataOptions:
    httpEndpoint: enabled
    httpTokens: required  # ← Mejora seguridad.
    httpPutResponseHopLimit: 2
  role: KarpenterNodeRole-eks-pdn
  securityGroupSelectorTerms:
  - tags:
      Environment: pdn
  subnetSelectorTerms:
  - tags:
      Environment: pdn
  tags:
    Environment: pdn
    CostCenter: C103500093
    Name: eks-pdn-karpenter-node
  userData: |  # ← **Optimizado**: Targets ↓40% (4xl=30GB,8xl=60GB).
    # [Script original pero MODIFICA get_target_size_by_suffix]
    get_target_size_by_suffix() {
      case $size_suffix in
        4xlarge) echo 30 ;;  # ↓40%
        8xlarge|9xlarge) echo 60 ;;  # ↓40%
        *) echo 40 ;;
      esac
    }
    # Resto script igual...
    # + /usr/bin/nodeadm init