apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: karpenter-spot-kafka:karpenter.sh/NodePool:karpenter/spot
    karpenter.sh/nodepool-hash: "2280763594660432461"
    karpenter.sh/nodepool-hash-version: v3
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"karpenter.sh/v1","kind":"NodePool","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"karpenter-spot-kafka:karpenter.sh/NodePool:karpenter/spot"},"name":"spot"},"spec":{"disruption":{"consolidateAfter":"1m","consolidationPolicy":"WhenEmptyOrUnderutilized"},"limits":{"cpu":1000},"template":{"spec":{"expireAfter":"720h","nodeClassRef":{"group":"karpenter.k8s.aws","kind":"EC2NodeClass","name":"defaultspot"},"requirements":[{"key":"kubernetes.io/arch","operator":"In","values":["amd64"]},{"key":"kubernetes.io/os","operator":"In","values":["linux"]},{"key":"karpenter.sh/capacity-type","operator":"In","values":["spot"]},{"key":"karpenter.k8s.aws/instance-category","operator":"In","values":["c","m","r"]},{"key":"karpenter.k8s.aws/instance-generation","operator":"Gt","values":["2"]}]}}}}
  creationTimestamp: "2025-10-05T20:15:56Z"
  generation: 2
  name: spot
  resourceVersion: "8548717"
  uid: 60f5dc3f-71d7-492e-a550-6b99910d239c
spec:
  disruption:
    budgets:
    - nodes: 10%
    consolidateAfter: 1m
    consolidationPolicy: WhenEmptyOrUnderutilized
  limits:
    cpu: 1000
  template:
    spec:
      expireAfter: 720h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: defaultspot
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values:
        - m
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values:
        - "2"
status:
  conditions:
  - lastTransitionTime: "2025-10-05T20:15:56Z"
    message: ""
    observedGeneration: 2
    reason: ValidationSucceeded
    status: "True"
    type: ValidationSucceeded
  - lastTransitionTime: "2025-10-05T20:16:10Z"
    message: ""
    observedGeneration: 2
    reason: NodeClassReady
    status: "True"
    type: NodeClassReady
  - lastTransitionTime: "2025-10-06T14:07:05Z"
    message: Failed to register node
    observedGeneration: 2
    reason: RegistrationFailed
    status: "False"
    type: NodeRegistrationHealthy
  - lastTransitionTime: "2025-10-06T14:01:44Z"
    message: ""
    observedGeneration: 2
    reason: Ready
    status: "True"
    type: Ready
  nodeClassObservedGeneration: 1
  resources:
    cpu: "2"
    ephemeral-storage: 20Gi
    memory: 7577Mi
    nodes: "1"
    pods: "29"
    vpc.amazonaws.com/pod-eni: "9"
