apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: spotvng
spec:
  disruption:
    budgets:
    - duration: 12h
      nodes: "0"
      schedule: 0 11 * * mon-fri
    - nodes: 10%
    consolidateAfter: 20m
    consolidationPolicy: WhenEmptyOrUnderutilized
  limits:
    cpu: 1000
  template:
    spec:
      expireAfter: 720h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: spotvng
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["spot", "on-demand"]
      - key: karpenter.k8s.aws/instance-size
        operator: In
        values:
        - 4xlarge
        - 8xlarge
        - 9xlarge
      - key: "karpenter.k8s.aws/instance-category"
        operator: In
        values: ["c", "m", "g", "r", "t", "i"]
      - key: "karpenter.k8s.aws/instance-generation"
        operator: Gt
        values: ["4"]