apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: karpenter-project
  source:
    repoURL: oci://public.ecr.aws/karpenter/karpenter
    targetRevision: "1.0.8"  # Versión estable más reciente de Karpenter
    chart: ""
    helm:
      values: |
        # Configuración para Karpenter v1.0+
        settings:
          clusterName: poc-kafka2
          # Para AWS
          aws:
            defaultInstanceProfile: KarpenterNodeInstanceProfile-poc-kafka2
            enablePodENI: false
            enableENILimitedPodDensity: true
        
        # Configuración del controlador
        controller:
          image:
            repository: public.ecr.aws/karpenter/karpenter
          resources:
            requests:
              cpu: 1
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi
        
        # Service Account con anotación para IRSA
        serviceAccount:
          create: true
          name: karpenter
          annotations:
            eks.amazonaws.com/role-arn: "arn:aws:iam::851725646489:role/KarpenterNodeRole-poc-kafka2"
        
        # Tolerancias para el controlador
        tolerations:
          - key: CriticalAddonsOnly
            operator: Exists
        
        # Configuración de afinidad
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: karpenter.sh/provisioner-name
                  operator: DoesNotExist
        
        # Configuración de logs
        logLevel: info
        
        # Configuración del webhook
        webhook:
          enabled: true
          port: 8443
  
  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  revisionHistoryLimit: 5