# argocd/nodepool.yaml - Configuración de NodePool para Karpenter
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-nodepool
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: karpenter-project
  source:
    repoURL: https://github.com/bcocbo/karpenter-gitops  # Tu repositorio GitOps
    targetRevision: main
    path: nodepool
  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true