apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: defaultspot
spec:
  role: "KarpenterNodeRole-eks-cloud" # replace with your cluster name
  amiSelectorTerms:
    - alias: "al2023@v20250920"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: eks-cloud # replace with your cluster name
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: eks-cloud # replace with your cluster name